services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitorpass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  prometheus:
    image: prom/prometheus
    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - "3000:3000"

    restart: unless-stopped

  sql-exporter:
    image: burningalchemist/sql_exporter
    container_name: sql-exporter

    ports:
      - "9399:9399"
    command:
      - "-config.file=/config.yml" 
    volumes:
      - ./sql_exporter.yml:/config.yml

    restart: unless-stopped

  zookeeper:

    image: confluentinc/cp-zookeeper:7.5.0

    container_name: zookeeper

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

    ports:
      - "2181:2181"


  kafka:

    image: confluentinc/cp-kafka:7.5.0

    container_name: kafka

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"

    environment:

      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  postgres_data: