global:
  scrape_timeout_offset: 500ms

collector_files:
  - "./os.collector.yml"

jobs:
  - job_name: os_job

    collectors:
      - os_collector

    static_configs:
      - targets:
          main:
            data_source_name: 'postgresql://monitor:monitorpass@postgres:5432/monitoring?sslmode=disable'